application: jbstatusboard
version: 2
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

handlers:
# URLS for testing
#- url: /tests
#  static_dir: testing
#  login: required

#- url: /runner
#  script: runner.py
#  login: required

- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js
  
- url: /widget
  static_dir: static/widget

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /check
  script: stashboard.py
  secure: optional  
  
- url: .*
  script: main.py
  secure: optional
  

skip_files: |
 ^(.*/)?(
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (dev/.*)|
 (tests/.*)|
 (docs/.*)|
 (.*\.markdown)|
 (license\.txt)|
 (setup.py)
 )$